### ISSUE TITLE
Feature: look at world weather API

### ISSUE THREAD

**Issue by SpudGunMan** [SpudGunMan/meshing-around#23]
https://openweathermap.org/current
Has a freemium style API 

https://open-meteo.com/en/docs
Free

**Comment by Hailo1999** [comment]
with open-meteo 
`Only for non-commercial use and less than 10.000 daily API calls. See [Terms](https://open-meteo.com/en/terms) for more details.`
but i think there will not be so much access to this feature

**Comment by SpudGunMan** [comment]
> open-meter has a interesting issue on pi it won't work without downloading a SDK package as well github.com/[open-meteo/open-meteo/issues/766](https://github.com/open-meteo/open-meteo/issues/766)

this issue appears to now be resolved! 👏

**Comment by SpudGunMan** [comment]
try out the feature with a `git pull && git checkout worldwx`
