### ISSUE TITLE
fail to respond over tcp

### ISSUE THREAD

**Issue by SpudGunMan** [SpudGunMan/meshing-around#25]
Report by @Hailo1999 pico won't work well since adding 2nd radio feature 

https://github.com/meshtastic/firmware/issues/3618

Also could be the onRx function consuming the interface need to test

**Comment by SpudGunMan** [comment]
if the issue was related to serial congestion this will help identify

**Comment by Hailo1999** [comment]
No, the PicoPI can only be reached via IP.

**Comment by SpudGunMan** [comment]
you could use the serial headers to attach, I want to diagram this some day for how-to. do you have issues still with the fix in place?

**Comment by SpudGunMan** [comment]
> No, the PicoPI can only be reached via IP.
its buffering serial over TCP, the TCP stuff is buggy as far as I know

**Comment by Hailo1999** [comment]
I will do the test tomorrow. To do this I have to remove the PicoPi from the mast. Then I'll test whether the error is also present with the serial interface.

**Comment by SpudGunMan** [comment]
got a fix in for TCP nodes

**Comment by SpudGunMan** [comment]
closing for now - appears resolved
