### ISSUE TITLE
Feature request: color coding of messages

### ISSUE THREAD

**Issue by Hailo1999** [SpudGunMan/meshing-around#27]
Display messages that are output in the command line in color. e.g. System red, direct messages in green, other channel messages in blue etc... so you can quickly distinguish what was written

**Comment by Hailo1999** [comment]
Like:

![output](https://github.com/user-attachments/assets/1ad48f9c-eb57-4105-9af2-2de66d9d6866)

**Comment by SpudGunMan** [comment]
Hey that looks nice!

 - need to rebuild a proper logger function. 

Also could log to disk
