### ISSUE TITLE
feature request for loging system

### ISSUE THREAD

**Issue by Hailo1999** [SpudGunMan/meshing-around#50]
Feels good to have the log. can you maybe split only error always logging, info af wish, and debug only if set in. So in 3 different stages. I don't know how to get this better.

like 

1.  info --->  not so important to log  becaus the most of this are messages going in and out (i think the most where log to mesagges if is turn on)

2. warning  ---> log alltimes

3. debug  ---> log only when requested and i think in past we do not need to log this events

**Comment by SpudGunMan** [comment]
you can set the logger here https://github.com/SpudGunMan/meshing-around/blob/6f3e3a79572648cc71305810369369e497bf5672/modules/log.py#L63 to something like INFO to not see the DEBUG logs
