### ISSUE TITLE
feature request: daily weather report

### ISSUE THREAD

**Issue by eric-becker** [SpudGunMan/meshing-around#51]
It would be nice to set an interval for automated weather reports (morning weather) on a specific channel at a specific time.

**Comment by SpudGunMan** [comment]
so I have a basic working tooling in place for this but I haven't thought of a good way to handle the settings yet so for now this is code only configurations. grab a copy of the code and modify it as you need (git pulls will overwrite your changes)

enable this switch https://github.com/SpudGunMan/meshing-around/blob/c4ef1251c9d4e35f3d3965af7d1f6a4ffb82c013/modules/settings.py#L27

and then see these lines of code to config jobs to schedule. 
https://github.com/SpudGunMan/meshing-around/blob/c4ef1251c9d4e35f3d3965af7d1f6a4ffb82c013/mesh_bot.py#L425-L435

this is the most flexible way to implement this function with the bot, I have at the moment anyway!
