### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AngryKiwiNZ** [SpudGunMan/meshing-around#59]
Hey Team!

Can I please suggest that if someone enters 'help' (without '') that the system returns the output of cmd instead of sending to the LLM.

I'm finding people who message without realising it's a bot with LLM don't know how to find their way to the menu. Everything they write executes the LLM and they miss out on all the goodness for sun/wx/hfcond etc.

Thanks!

**Comment by SpudGunMan** [comment]
see if the latest version handles this well?

**Comment by AngryKiwiNZ** [comment]
That's great thank you. It will help new users to find the cmd menu and all the useful functions. Thanks!
